### ISSUE TITLE
[Feature request]: Hide Vanadium for GrapheneOS devices

### ISSUE THREAD

**Issue by Alerymin** [techlore/Plexus-app#37]
### Description

GrapheneOS has the Vanadium browser preinstalled. But it has the same app id as Chromium: `org.chromium.chrome` which can lead to wrong ratings on Chromium

It almost led to me making a rating that way 

### Terms

- [X] This feature is not present in the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
- [X] This is not a duplicate of another feature request.

**Comment by StellarSand** [comment]
When I searched for "Vanadium" it returns 2 results, both with different package names.
<img src="https://github.com/user-attachments/assets/d6ec7491-d0ec-44c1-b610-cf139ef2aa38" width=250>

So....my question is...what happened here? :thinking:

**Comment by Rathmox** [comment]
> So....my question is...what happened here? 🤔
The package name used to be app.vanadium.browser

**Comment by Rathmox** [comment]
Ok no nevermind, I noticed the issue,

Vanadium actually used to be `org.chrome.chromium` (my install is more than 2 years old) but then got renamed to `app.vanadium.browser`, which explains why my app id is `org.chrome.chromium`: https://grapheneos.org/releases#2023020200

![Screenshot_20240818-115210](https://github.com/user-attachments/assets/61ecfee7-9206-4c95-9efc-85866e4a56d8)

**Comment by StellarSand** [comment]
Okay so Vanadium with the `org.chrome.chromium` package name needs to be hidden in GrapheneOS, right?

**Comment by Rathmox** [comment]
I'm not sure anymore, as old GrapheneOS installs should, but most recent ones should not as they could install chromium.

It should be hidden only if `org.chromium.chrome` is a system app

**Comment by Rathmox** [comment]
Basically add a name + id check

**Comment by StellarSand** [comment]
I’ve implemented this feature, but I’m beginning to question its necessity. The [original ungoogled chromium for android](https://github.com/ungoogled-software/ungoogled-chromium-android) has been abandoned, with no updates for the past two years. Given this situation, it might be acceptable for Vanadium to utilize the `com.chromium.chrome` package.

**Comment by Rathmox** [comment]
it has been 1 year since Vanadium changed it's id.
So yes, nobody should use ungoogled chromium anymore.
but both Vanadium apps are still the same.

I don't know either if we should do it too tbh

**Comment by StellarSand** [comment]
A search in the Plexus database shows that Vanadium, with the `com.chromium.chrome` package name is still being used by people on the latest versions of GrapheneOS. Since ungoogled chromium is not being used by anyone, given that it has been abandoned, I’ve decided to keep things as they are.
